### ISSUE TITLE
Docker mysql does not properly creating specified database during initialization

### ISSUE THREAD

**Issue by Juncheng-Li** [geoffreychen831/AABKoala#34]
```yml
environment:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: dockerTest
  MYSQL_USER: client3
  MYSQL_PASSWORD: AA-koala123456
```

already specified initial database, but the docker does not create the specified database if volume mapping is set.
